name: counter
description: A Very Good Project created by Very Good CLI.
version: 1.0.0+1
publish_to: none

environment:
    sdk: ">=3.1.0 <4.0.0"

dependencies:
    flutter:
        sdk: flutter
    state_beacon:
        path: ../../packages/state_beacon

dependency_overrides:
  state_beacon_core: 
    path: ../../packages/state_beacon_core
  state_beacon_flutter: 
    path: ../../packages/state_beacon_flutter
    
dev_dependencies:
    flutter_test:
        sdk: flutter
    mocktail: ^1.0.0
    very_good_analysis: ^5.1.0

flutter:
    uses-material-design: true
