name: vgv_best_practices
description: Very Good Ventures default app template using state_beacon
version: 1.0.0+1
publish_to: none

environment:
    sdk: ">=3.1.0 <4.0.0"

dependencies:
    flutter:
        sdk: flutter
    flutter_localizations:
        sdk: flutter
    intl: ^0.20.2
    provider: ^6.1.5+1
    state_beacon:
        path: ../../packages/state_beacon

dependency_overrides:
  state_beacon_core: 
    path: ../../packages/state_beacon_core
  state_beacon_flutter: 
    path: ../../packages/state_beacon_flutter

dev_dependencies:
    flutter_test:
        sdk: flutter
    mocktail: ^1.0.0
    very_good_analysis: ^10.0.0

flutter:
    uses-material-design: true
    generate: true
