name: bench
description: A Very Good Project created by Very Good CLI.
version: 1.0.0+1
publish_to: none

environment:
    sdk: ">=3.1.0 <4.0.0"

dependencies:
    flutter:
        sdk: flutter
    benchmark_harness: ^2.2.2
    state_beacon:
        path: ../../packages/state_beacon


flutter:
    uses-material-design: true
