name: old_code
description: A sample command-line application.
version: 1.0.0
publish_to: none
# repository: https://github.com/my_org/my_repo

environment:
  sdk: ^3.3.2

# Add regular dependencies here.
dependencies:
  state_beacon_core: ^2.0.1
  benchmark_harness: ^2.2.2

dev_dependencies:
  lints: ^6.0.0
